In [ ]:
import numpy as np

In [ ]:
num_pop = 10
num_dim = 5
up = 5
low = 0

In [ ]:
population = np.random.rand(num_pop, num_dim)

In [ ]:
population = [low + (x * (up-low)) for x in population]
population = np.round(population,4)

In [ ]:
print(population[5])
print(len(population))

[4.9568 3.1471 2.9356 3.0072 0.3709]
10


In [ ]:
def fitness_func(x):
  return x**2



In [ ]:
temp = fitness_func(population[2])
temp1 = fitness_func(population[3])

print(population[2])
print(temp)
print(sum(temp))
print(sum(temp1))
print(temp>temp1)
if sum(temp)<= sum(temp1):
  print(1)

[3.9494 3.1838 1.7469 1.1759 1.6858]
[15.59776036 10.13658244  3.05165961  1.38274081  2.84192164]
33.010664860000006
34.058384700000005
[ True  True False False  True]
1


In [ ]:
def differential_evolution(fitness_func, dim_num, lw_bound, up_bound, pop_size, mutation_fac, cr_prob, break_point):

  #initlize population
  population = np.random.rand(pop_size, dim_num)
  population = [lw_bound + (x * (up_bound-lw_bound)) for x in population]
  population = np.round(population, 4)

  #evaluate
  fitness_scores = [np.sum(fitness_func(x)) for x in population]
  fitness_scores = np.round(fitness_scores, 4)

  for generation in range(break_point):
    for i in range(len(population)):

      #mutation
      idx = [k for k in range(len(population)) if k != i]
      x_1, x_2, x_3 = population[np.random.choice(idx, 3, replace=False)]

      mutation_vector = x_1 + mutation_fac * (x_2 - x_3)
      mutation_vector = np.round(mutation_vector, 4)
      mutation_vector = np.clip(mutation_vector, lw_bound, up_bound)

      #crossover
      d_rand = np.random.randint(0, dim_num)
      trial_vector = np.zeros(dim_num)
      for j in range(dim_num):
        if np.random.rand() < cr_prob or j == d_rand:
          trial_vector[j] = mutation_vector[j]
        else:
          trial_vector[j] = population[i][j]

      #selectiion
      trial_fitness = np.sum(fitness_func(trial_vector))
      trial_fitness = np.round(trial_fitness, 4)
      if trial_fitness < fitness_scores[i]:
              population[i] = trial_vector
              fitness_scores[i] = trial_fitness

    if generation % 100 == 0 :
      best_index = np.argmin(fitness_scores)
      best_solution = population[best_index]
      best_fitness = fitness_scores[best_index]
      print(f'best_solution is : {best_solution}, best_fitness is : {best_fitness}')

  return best_solution, best_fitness


In [ ]:
best_sol , best_fit = differential_evolution(fitness_func, 10, -10, 10, 1000, 1.5, 0.2, 500)


best_solution is : [-1.0993  0.1542  4.6722  0.8177 -1.8505  0.19   -0.1568  3.7152  5.377
  3.5696], best_fitness is : 82.6722
best_solution is : [-0.6765 -0.112   0.0578 -1.4576  0.286   0.1131  0.9476 -0.1328 -0.8219
  0.1303], best_fitness is : 4.30080176
best_solution is : [-0.0348 -0.012  -0.1445 -0.0754  0.1848  0.0532  0.2174 -0.1177 -0.0629
 -0.05  ], best_fitness is : 0.13247418999999996
best_solution is : [ 0.0208 -0.0071 -0.0665  0.0203  0.0867  0.0227  0.058   0.0296 -0.0031
 -0.0294], best_fitness is : 0.018463700000000003
best_solution is : [ 0.0082  0.0054 -0.0103  0.0062  0.0256 -0.005   0.0067  0.0106 -0.0028
 -0.0065], best_fitness is : 0.00112863
